---
title: "Factors Affecting EV Adoption in the U.S."
author: "Nataraj.Patankar.Tiwari.Wavre"
date: "2025-04-24"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Introduction


## Background and Motivation 


## Information on Datasets


## Setting up the Session
```{r setup, message=FALSE, warning=FALSE, results='hide'}
#Installing and loading packages
#install.packages("ggforce")
#install.packages("readxl")
library(tidyverse)
library(lubridate)
library(here)
library(ggplot2)
library(stringr)
library(cowplot)
library(ggforce)
library(scales)
library(dplyr)
library(readxl)
library(sf)
library(leaflet)
library(mapview); mapviewOptions(fgb = FALSE)
```

## Importing and Cleaning Datasets

```{r datasets, message=FALSE, warning=FALSE}
#EV Registration Data
LDV_Data <- read_excel("Data/Raw/2016-2023 LDV Registration Data.xlsx")
colnames(LDV_Data) [c(3,4)] <- c("EV", "PHEV")
LDV_Clean <- LDV_Data %>%
  mutate(Total_EV = EV + PHEV) %>%
  select(Year, State, Total_EV, EV, PHEV)

#write.csv(LDV_Clean, "Data/Processed/LDV_Clean.csv", row.names = FALSE)

#Income Data
Income_Data <- read.csv("Data/Raw/Average Income Data by State.csv")
Income_Clean <- Income_Data %>%
  mutate(State = str_trim(str_remove(State, "\\*")))

#write.csv(Income_Clean, "Data/Processed/Avg_Income_Clean.csv", row.names = FALSE)

#Population Data
Pop_Data <- read_excel("Data/Raw/Population 2020-2024.xlsx")
colnames(Pop_Data) [c(2,3,4,5)] <- c("Pop_2020","Pop_2021","Pop_2022","Pop_2023")

Pop_clean <- Pop_Data %>%
  pivot_longer(cols = starts_with("Pop_"), names_to = "Year", names_prefix = "Pop_", values_to = "Population") %>%
  select(Year, State, Population) %>%
  mutate(Year = as.numeric(Year))

#write.csv(Pop_clean, "Data/Processed/Population_Clean.csv", row.names = FALSE)

#Fuel Stations 
Fuel_Stations <- read.csv("Data/Raw/Fuel_Stations_Historical_Data.csv")



```

## Creating Data Plots
```{r}
# Creating GGPlot of Statewise Total EV Registrations
ggplot(LDV_Clean, aes(x = Year, y = `Total_EV`, color = State)) +
  geom_line(size = 1) +
  labs(
    title = "Total EV Registrations by State (2016–2023)",
    x = "Year",
    y = "Number of EVs Registered",
    color = "State"
  ) +
  theme_minimal(base_size = 14)

```

```{r}
#4 Creating a map of Charging Stations all of US - Includes Mainland USA, Alaska and Hawaii

#Reading Datafile
States_sf <- st_read( here('./Data/Raw/cb_2018_us_state_5m/cb_2018_us_state_5m.shp'))

bbox_us <- st_bbox(c(xmin = -179, xmax = -66, ymin = 18.5, ymax = 72), crs = st_crs(States_sf))
States_sf_cropped <- st_crop(States_sf, bbox_us)

mapviewOptions(basemaps = "OpenStreetMap")
mapview(States_sf_cropped)

# Reading Charging Station Data
str(stations)

#Selecting required columns and Removing Rows which do not have valid Latitude and Logitude data
ev_stations2 <- stations %>%
  filter(Fuel.Type.Code == "ELEC") %>%
  select(Fuel.Type.Code, Latitude, Longitude) %>%
  filter(
    !is.na(Longitude), !is.na(Latitude),
    Latitude >= 18.5, Latitude <= 72,
    Longitude <= -66, Longitude >= -179
  )

write.csv(ev_stations2, "Data/Processed/EVStation_Locations.csv", row.names = FALSE)

Stations.sf <- ev_stations2%>%
  st_as_sf(
    coords = c('Longitude','Latitude'),
    crs=4269
  )

Plot_EVStationLocations <- ggplot()+
  geom_sf(data = States_sf, fill="white", size = 0.5) +
  geom_sf(data = Stations.sf, color = "red", size = 0.2)+
  ggtitle("EV Station Locations in the US")+
  coord_sf(
    xlim = c(-179, -66), 
    ylim = c(18.5, 72),    
    expand = FALSE)
Plot_EVStationLocations
```


```{r}
# Map of just mainland

bbox_us2 <- st_bbox(c(xmin = -125, xmax = -66, ymin = 24, ymax = 50), crs = st_crs(States_sf))
States_sf_cropped2 <- st_crop(States_sf, bbox_us2)
mapview(States_sf_cropped2)

#Selecting required columns and Removing Rows which do not have valid Latitude and Logitude data
ev_stations3 <- stations %>%
  filter(Fuel.Type.Code == "ELEC") %>%
  select(Fuel.Type.Code, Latitude, Longitude) %>%
  filter(
    !is.na(Longitude), !is.na(Latitude),
    Latitude >= 24, Latitude <= 50,
    Longitude <= -66, Longitude >= -125
  )

Stations.sf2 <- ev_stations3%>%
  st_as_sf(
    coords = c('Longitude','Latitude'),
    crs=4269
  )

Plot_EVStationLocations2 <- ggplot()+
  geom_sf(data = States_sf, fill="white", size = 0.5) +
  geom_sf(data = Stations.sf2, color = "red", size = 0.2)+
  ggtitle("EV Station Locations in the Mainland US")+
  coord_sf(
    xlim = c(-125, -66), 
    ylim = c(24, 50),    
    expand = FALSE)
Plot_EVStationLocations2
```

